export const translations: Record<"es" | "en", {
  personalInfo: {
    name: string;
    location: string;
    email: string;
    github: string;
    linkedin: string;
  };
  workExperience: Array<{
    company: string;
    location: string;
    position: string;
    period: string;
    achievements: string[];
  }>;
  projects: Array<{
    title: string;
    github: string;
    description: string;
  }>;
  education: Array<{
    institution: string;
    location: string;
    degree: string;
    period: string;
    achievements?: string[];
  }>;
  skills: {
    programmingLanguages: string[];
    frontendDevelopment: string[];
    backendDevelopment: string[];
    databaseAndStorage: string[];
    cloudAndDevOps: string[];
  };
}> = {
    en: {
    personalInfo: {
      name: "Andrés E. Sánchez García",
      location: "Santa Cruz de Tenerife, Spain",
      email: "andrestf99@gmail.com",
      github: "https://github.com/CodeEspu",
      linkedin: "https://www.linkedin.com/in/andres-s%C3%A1nchez-garc%C3%ADa/",
    },
    workExperience: [
      {
        company: "Sound Black SLU",
        location: "Santa Cruz de Tenerife, Spain",
        position: "🔊 Audiovisual Technician",
        period: "June 2024 - Sept 2024",
        achievements: [
          "➜ Assembly of sound, video, and lighting equipment for events.",
          "➜ Technical project management, problem-solving, and team coordination.",
        ],
      },
      {
        company: "Sonopluss SL",
        location: "Santa Cruz de Tenerife, Spain",
        position: "🔊 Sound Technician",
        period: "Mar 2024 - June 2024",
        achievements: [
          "➜ Assembly and organization of sound equipment and structures.",
          "➜ Attention to detail, organization, and teamwork.",
          "➜ Internship period",
        ],
      },
    ],
    projects: [
      {
        title: "Blue Team Lab on Docker",
        github: "https://github.com/CodeEspu/Docker-BlueTeam",
        description: "Deployed a security monitoring environment in Docker containers:<br />🔹 Suricata (IDS) → Analyzes real-time network traffic to detect intrusions<br />🔹 Wazuh (SIEM) → Enriches and correlates security logs generated by Suricata<br />🔹 Filebeat → Collects and forwards events to Logstash for processing<br />🔹 ELK Stack (Elasticsearch, Logstash, Kibana) → Stores, processes, and visualizes security alerts and metrics"
      },
      {
        title: "Custom Password Dictionary Generator",
        github: "https://github.com/CodeEspu/genpass",
        description: "I developed a Python script designed to automatically generate personalized password dictionaries based on personal data such as first name, last names, birth year, and children's names.<br /><br /> The tool creates textual variations, abbreviations, and adds special characters to generate realistic, context-aware password combinations."
      },
      {
        title: "SSRF to XSS: Exploitation Simulation in PDF Generation",
        github: "https://github.com/CodeEspu/SSRFtoXSS",
        description: "This project demonstrates an attack chain where an SSRF vulnerability is chained to achieve an XSS. The simulation details how wkhtmltopdf can be forced to execute malicious JavaScript on the server, confirming the execution of XSS in the backend. 💻🛡️ "
      }
    ],
    education: [
      {
        institution: "University of La Laguna",
        location: "Remote",
        degree: "Diginnova Program: Innovation, Digital Transformation, and Sustainability",
        period: "Apr 2025 - Jun 2026",
        achievements: [
          "➜ Dual training program focused on employability, combining 7 months of online education in innovation, digitalization, and sustainability, followed by 4 months of paid internships in companies based in the Canary Islands.",
          "➜ Includes a university-issued certification and practical content aligned with the current professional landscape.",
          ],
      },
      {
        institution: "CIFP César Manrique",
        location: "Santa Cruz de Tenerife, Spain",
        degree: "Specialization Course in Cybersecurity IT",
        period: "Sept 2024 - Jun 2025",
        achievements: [
          "➜ Class Representative.",
          "➜ Development of Practical Projects.",
          "➜ Participation in Cybersecurity Events (e.g Hackr0n)."
          ],
      },
      {
        institution: "CIFP César Manrique",
        location: "Santa Cruz de Tenerife, Spain",
        degree: "Telecommunications and Computer Systems",
        period: "Sept 2022 - Jun 2024",
      },
      {
        institution: "IES Puntalarga",
        location: "Santa Cruz de Tenerife, Spain",
        degree: "High School Diploma in Technology Sciences",
        period: "Sept 2016 - Jun 2018",
      },
    ],
    skills: {
      programmingLanguages: ["Python", "C#", "Bash", "Powershell", "HTML", "CSS", "SQL Queries"],
      frontendDevelopment: ["Wireshark", "Burp Suite CE", "Metasploit", "JohnTheRipper", "CrackMapExec", "OWASP Zap",
    "Setoolkit", "Shodan", "Ettercap", "Haschat", "Nikto", "Hydra", "Aircrack-ng", "SQLmap", "BeEF", "Dirbuster",
    "Cewl", "TheFatRat", "Nessus"],
      backendDevelopment: ["SIEM", "Wazuh", "ELK", "pfsense", "Kibana", "Shodan", "Suricata", "GnuPG", "OpenSSL", "Snort", "Zabbix",
         "RADIUS Server", "Cisco Packet Tracer", "ElasticSearch", "Logstash", "Nginx", "PostgreSQL", "MariaDB", "Apache"],
      databaseAndStorage: ["Volatility", "Autopsy", "Registry Explorer", "iLEAPP", "ALEAPP", "FTK Imager",
    "Cellebrite UFED", "Log2Timeline", "HxD Editor", "Caine"],
      cloudAndDevOps: ["GitHub", "Docker", "Google Dork", "Genymotion"],
    },
  },
  es: {
    personalInfo: {
      name: "Andrés E. Sánchez García",
      location: "Santa Cruz de Tenerife, España",
      email: "andrestf99@gmail.com",
      github: "https://github.com/CodeEspu",
      linkedin: "https://www.linkedin.com/in/andres-s%C3%A1nchez-garc%C3%ADa/",
    },
    workExperience: [
      {
        company: "Sound Black SLU",
        location: "Santa Cruz de Tenerife, España",
        position: "🔊 Técnico Audiovisual",
        period: "Junio 2024 - Septiembre 2024",
        achievements: [
          "➜ Montaje de equipos de sonido, vídeo e iluminación para eventos.",
          "➜ Gestión técnica de proyectos, resolución de problemas y coordinación de equipos.",
        ],
      },
      {
        company: "Sonopluss SL",
        location: "Santa Cruz de Tenerife, España",
        position: "🔊 Técnico de Sonido",
        period: "Mar 2024 - Junio 2024",
        achievements: [
          "➜ Montaje y organización de equipos de sonido y estructuras.",
          "➜ Atención al detalle, organización y trabajo en equipo.",
          "➜ Periodo de prácticas",
        ],
      },
    ],
    projects: [
      {
        title: "Laboratorio Blue Team en Docker",
        github: "https://github.com/CodeEspu/Docker-BlueTeam",
        description: "Implementé un entorno de monitorización de seguridad en contenedores Docker:<br />🔹 Suricata (IDS) → Analiza el tráfico de red en tiempo real para detectar intrusiones<br />🔹 Wazuh (SIEM) → Enriquece y correlaciona los logs de seguridad generados por Suricata<br />🔹 Filebeat → Recolecta y envía los eventos hacia Logstash para su procesamiento<br />🔹 ELK Stack (Elasticsearch, Logstash, Kibana) → Almacena, procesa y visualiza alertas y métricas de seguridad"
      },
      {
        title: "Generador Personalizado de Diccionarios de Contraseñas",
        github: "https://github.com/CodeEspu/genpass",
        description: "Desarrollé un script en Python diseñado para generar automáticamente diccionarios de contraseñas personalizados a partir de datos personales como nombre, apellidos, año de nacimiento y nombres de hijos.<br /><br />La herramienta crea variaciones textuales, abreviaturas y añade caracteres especiales para generar combinaciones de contraseñas realistas y contextualizadas."
      },
      {
        title: "SSRF a XSS: Simulación de Explotación en Generación de PDFs",
        github: "https://github.com/CodeEspu/SSRFtoXSS",
        description: "Este proyecto demuestra una cadena de ataque donde una vulnerabilidad de SSRF es encadenada para lograr un XSS. La simulación detalla cómo se puede forzar a wkhtmltopdf a ejecutar JavaScript malicioso en el servidor, confirmando la ejecución del XSS en el backend. 💻🛡️ "
      }
    ],
    education: [
      {
        institution: "Universidad de La Laguna",
        location: "Remoto",
        degree: "Programa Diginnova: Innovación, Transformación Digital y Sostenibilidad",
        period: "Abr 2025 - Jun 2026",
        achievements: [
          "➜ Formación dual orientada a la empleabilidad, con 7 meses de formación online en innovación, digitalización y sostenibilidad, seguida de 4 meses de prácticas remuneradas en empresas canarias.",
          "➜ Incluye certificación universitaria y contenidos aplicados a la realidad del entorno profesional actual",
          ],
      },
      {
        institution: "CIFP César Manrique",
        location: "Santa Cruz de Tenerife, España",
        degree: "Curso de Especialización en Ciberseguridad IT",
        period: "Sept 2024 - Jun 2025",
        achievements: [
          "➜ Delegado de clase.",
          "➜ Desarrollo de proyectos prácticos.",
          "➜ Participación en eventos de Ciberseguridad (e.g Hackr0n)."
          ],
        
      },
      {
        institution: "CIFP César Manrique",
        location: "Santa Cruz de Tenerife, España",
        degree: "Técnico en Sistemas de Telecomunicaciones e Informáticos",
        period: "Sept 2022 - Jun 2024",
      },
      {
        institution: "IES Puntalarga",
        location: "Santa Cruz de Tenerife, España",
        degree: "Bachillerato en Ciencias Tecnológicas",
        period: "Sept 2016 - Jun 2018",
      },
      
    ],
    skills: {
      programmingLanguages: ["Python", "C#", "Bash", "Powershell", "HTML", "CSS", "Consultas SQL"],
      frontendDevelopment: ["Wireshark", "Burp Suite CE", "Metasploit", "JohnTheRipper", "CrackMapExec", "OWASP Zap",
        "Setoolkit", "Shodan", "Ettercap", "Haschat", "Nikto", "Hydra", "Aircrack-ng", "SQLmap", "BeEF", "Dirbuster",
        "Cewl", "TheFatRat", "Nessus"],
      backendDevelopment: ["SIEM", "Wazuh", "ELK", "pfsense", "Kibana", "Shodan", "Suricata", "GnuPG", "OpenSSL", "Snort", "Zabbix",
         "RADIUS Server", "Cisco Packet Tracer", "ElasticSearch", "Logstash", "Nginx", "PostgreSQL", "MariaDB", "Apache"],
      databaseAndStorage: ["Volatility", "Autopsy", "Registry Explorer", "iLEAPP", "ALEAPP", "FTK Imager",
    "Cellebrite UFED", "Log2Timeline", "HxD Editor", "Caine"],
      cloudAndDevOps: ["GitHub", "Docker", "Google Dork", "Genymotion"],
    },
  },
};







